### ISSUE TITLE
"repl process died unexpectedly: exit status 2"

### ISSUE THREAD

**Issue by Mattypat** [ghost-2e/Starscape-System-Finder#1]
<img width="1440" alt="Screenshot 2023-05-09 at 8 55 52 PM" src="https://github.com/iStagnant/Starscape-System-Finder/assets/131541374/e34ad5fd-5d0d-44c3-8762-f7d5bd179642">
Uhhhh... would really like to use this but I can't.

**Comment by iStagnant** [comment]
After all these years I'm glade someone is using this I almost forgot it existed. Anyways the code is working fine it's just a change in how the Run button in replit work your systems are: Meopleere
Trauzalt
Staomle

I'll push a commit fixing this.
PS: Sorry for making you wait 2 days for a fix.

**Comment by Mattypat** [comment]
Thanks. This means a lot. Hope you didn't go to too much trouble for this.
